
satkit constants:
  # What precision is treated as equal when comparing annotation boundaries.
  epsilon: 0.00001

data properties:
  # This tells SATKIT which metadata importer to use.
  data source: AAA

  # Speaker id is used in the output csv file.
  speaker id: gam-1-2
  # This is where we read the wavs and metadata from.
  data directory: local_data/single_file
  # This will be used as the name of the output wav and TextGrid.
  outputfilename: local_data/File004

  # Strict YAML file specifying recordings to be excluded based 
  # on both prompts and file names.
  exclusion list: 
  # Consists of words followed by their segments in arbitrary transcription.  
  pronunciation dictionary: local_data/gam_mono_and_disyllables_for_automatic_segmentation.csv

flags:
  detect beep: True # Should onset beep detection be run?
  only words: False # Add only Utterance and Word Tiers.
  utterance: True # Add Utterance Tier.
  file: False # Add File Tier.
  test: False # Run on only the first 10 recordings.


