
# Please note that empty file or directory fields are
# interpeted as not available and represented by None. If you want to specify
# current working directory, use '.'

# What precision is treated as equal when comparing annotation boundaries.
epsilon: 0.00001

# Default parameters for a data run. Unless you happen to be me, you should
# probably change these, but do it by copying the file and giving a
# commandline argument. -Pertti     
data run parameter file: configuration/satkit_data_run_parameters.yaml

# GUI setup parameters
gui parameter file: configuration/satkit_gui_parameters.yaml