
satkit constants:
  # What precision is treated as equal when comparing annotation boundaries.
  epsilon: 0.00001
  # Height ratio of data display vs textgrid tier display. This does not control
  # directly the height of individual data displays nor individiual tier
  # displays, but instead controls the ratio between the sum of data displays vs
  # sum of tier displays.
  data/tier height ratios: 
    data: 3
    tier: 1
  # Default parameters for a data run. Unless you happen to be me, you should
  # probably change these, but do it by copying the file and giving a
  # commandline argument. -Pertti
  data run parameter file: satkit_default_parameters.yaml

data properties:
  # This tells SATKIT which metadata importer to use.
  data source: AAA

  # Speaker id is used in the output csv file.
  speaker id: gam-1-2
  # This is where we read the wavs and metadata from.
  data directory: local_data/single_file
  # This will be used as the name of the output wav and TextGrid.
  outputfilename: local_data/File004

  # Strict YAML file specifying recordings to be excluded based 
  # on both prompts and file names.
  exclusion list: 
  # Consists of words followed by their segments in arbitrary transcription.  
  pronunciation dictionary: local_data/gam_mono_and_disyllables_for_automatic_segmentation.csv

flags:
  detect beep: True # Should onset beep detection be run?
  only words: False # Add only Utterance and Word Tiers.
  utterance: True # Add Utterance Tier.
  file: False # Add File Tier.
  test: False # Run on only the first 10 recordings.


